# docker-compose.yml
version: '3.8'

services:
  mongo1:
    image: mongo:5.0
    container_name: mongo1
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo1-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - mongo-network

  mongo2:
    image: mongo:5.0
    container_name: mongo2
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo2-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - mongo-network

  mongo3:
    image: mongo:5.0
    container_name: mongo3
    restart: always
    ports:
      - "27019:27017"
    volumes:
      - mongo3-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - mongo-network

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    restart: always
    ports:
      - "27020:27017"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    networks:
      - mongo-network

volumes:
  mongo1-data:
  mongo2-data:
  mongo3-data:

networks:
  mongo-network:
    driver: bridge
